### ISSUE TITLE
discord.js no longer exists

### ISSUE THREAD

**Issue by SylverBean** [Butterstroke/MargarineBot#46] opened 2018-10-31 13:42 UTC
DX I had to default to the normal bc yours doesnt exist anymore. Just letting ya know lol

**Comment by AurelicButter** [comment] 2018-11-05 01:56
@vampymaria That's weird. I can't replicate this on my systems. It should install the master branch of the discord.js branch normally. I'm not sure what branch you used for this since both are essentially the same in the package.json file.

Might posting the error you got for me? It'd help me out a lot with this.

**Comment by SylverBean** [comment] 2018-11-14 00:40
" "discord.js": "github:hydrabolt/discord.js"," this git no longer exists ...

**Comment by AurelicButter** [comment] 2018-11-14 04:01
It does still exist, I've recently updated my discord.js package in the past couple of days and I didn't have any issue in finding it.

> I had to default to the normal

As in discord.js v11.4 normal? Suddenly, #47 is making a lot more sense if this is the case.

If you can please provide me with the following, that would be fantastic.
- Version that you are using (Found in your settings.json file)
- Steps on what you did to get this issue.
- Node.js version
- NPM version

Otherwise, a good workaround would be to run `npm install hydrabolt/discord.js` in the root folder and see what happens.

**Comment by SylverBean** [comment] 2018-11-17 01:01
I go to the link at it doesnt exist anymore, and yes. v11.4.2 I had to contact a few other people from the site I am hosting on to fix it bc I couldnt figure out the issue ... The npm ... uh ... "node": "8.x" idk npm ...

**Comment by AurelicButter** [comment] 2018-11-17 03:23
Yeah.... there's the reason why #47 is not right. You need that master branch (which is the v12 beta) to run the bot. There are a lot of changes from v11 to v12. Once this is resolved, it should also be resolved as far as I can tell. If not, I'll continue working from there.

The Node version checks out, so I'm going to assume the npm is good too.

> Link doesn't exist anymore

It's a Github link that is still valid. [github.com/hydrabolt/discord.js](github.com/hydrabolt/discord.js) will redirect to [github.com/discordjs/discord.js](github.com/discordjs/discord.js), the location of where v12 beta is but it's still good.

>The site I am hosting on

Site? Like Glitch?

**Comment by SylverBean** [comment] 2018-11-17 20:48
![image](https://user-images.githubusercontent.com/38189579/48665619-0e370380-ea80-11e8-9c2c-453e882672c5.png)
It doesnt exist ...

**Comment by AurelicButter** [comment] 2018-11-17 22:12
Rip. Looks like my link didn't quite work as intended.

https://github.com/hydrabolt/discord.js <- Copy paste that into a tab. That will work.

Edit: I didn't mean webpage, meant a tab.

**Comment by SylverBean** [comment] 2018-11-20 14:50
it took me to the regular discord.js?

**Comment by AurelicButter** [comment] 2018-11-20 21:30
No, that is the current v12-dev discord.js package that you've claimed doesn't exist. That's what the command `npm hydrabolt/discord.js` installs.

>Site? Like Glitch?

Still haven't heard an answer about these. If it is a site like Glitch, there might be a limitation so that you can only install published npm packages. Which would explain why this "doesn't exist" to you in the first place since discord.js v12-dev is not a published package. This is just my theory however, since I do not use sites like Glitch in the first place.

Edit: Quoted wrong.

**Comment by SylverBean** [comment] 2018-11-21 21:33
https://github.com/discordjs/discord.js is where it takes me ... which is the regular discord.js ... And yes, glitch ... They are the ones who told me the hydrabolt package no longer existed ... Discord.js docs takes me to this exact same link ...

**Comment by AurelicButter** [comment] 2018-11-21 23:23
I'll be closing this issue based on the fact that I've deemed this is a Glitch issue and not an issue with the code.

>And yes, glitch ... They are the ones who told me the hydrabolt package no longer existed

I believe that Glitch does not allow users to install unpublished npm packages, which would be the potential reason why the v12-dev of discord.js is "non-existent". However, this is just my theory as I do not use Glitch myself. This line just makes my theory just that much more true to me.

>https://github.com/discordjs/discord.js is where it takes me ... which is the regular discord.js

Clearly you did not read my message from 5 days ago about the links and what version of discord.js is there. You can easily check the version of that package through the package.json file if there are any questions about what version it is. The discord.js documentation is correct in terms of this since it is the right location of the v12-dev. v12-dev is the master branch of this repository.

If doing `npm install hydrabolt/discord.js` is failing, try doing `git+https://git@github.com/discordjs/discord.js.git`. I poked around Google for this, so I'm not sure how accurate this is. Otherwise, I can't help you on this anymore since I have no other ideas.

Any other issues involving installing this package, contact Glitch support. I can confirm that it does install properly on Windows 10 and Ubuntu 14.05 systems with Node 8.5+ as I have installed the package on both systems through the `npm install hydrabolt/discord.js` command over the duration that this issue has been open.

**Closed as completed by AurelicButter** 2018-11-21 23:23 UTC
Labels: Won't Fix
